# Generated by Django 4.2.1 on 2023-06-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(default='nb', max_length=100),
            preserve_default=False,
        ),
    ]
