version: '2.2'

services:
  web:
    build: .
    command: bash -c "python manage.py collectstatic --noinput && python manage.py makemigrations && python manage.py migrate && gunicorn GlobalSensorCloud.wsgi --workers 2 -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    expose:
      - 8000
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/app
#  celery:
#    build: .
#    command: celery -A GlobalSensorCloud worker --loglevel=INFO
#    volumes:
#      - .:/app
#    depends_on:
#      redis:
#        condition: service_healthy
#  redis:
#    image: redis:latest
#    healthcheck:
#      test: [ "CMD", "redis-cli", "ping" ]
#      interval: 5s
#      timeout: 10s
#      retries: 3