# Generated by Django 4.2.1 on 2023-05-26 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloudapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbientConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition_type', models.CharField(choices=[('Rain', 'Rain'), ('Snow', 'Snow'), ('Fog', 'Fog'), ('Other', 'Other')], max_length=10)),
                ('outdoor_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ground_temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('other_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('LIDAR', 'Lidar'), ('TOF', 'Tof Camera'), ('VISUAL', 'Visual Camera'), ('OTHERS', 'Others'), ('LEGACY', 'Legacy')], max_length=10)),
                ('status', models.CharField(max_length=10)),
                ('last_seen', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SystemOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_email', models.EmailField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='VizData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value1', models.IntegerField(null=True)),
                ('value2', models.IntegerField(null=True)),
                ('value3', models.IntegerField(null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viz', to='cloudapp.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='TofData2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value1', models.IntegerField(null=True)),
                ('value2', models.IntegerField(null=True)),
                ('value3', models.IntegerField(null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tofr', to='cloudapp.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='TofData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value1', models.IntegerField(null=True)),
                ('value2', models.IntegerField(null=True)),
                ('value3', models.IntegerField(null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tofm', to='cloudapp.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='TofData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('value1', models.IntegerField(null=True)),
                ('value2', models.IntegerField(null=True)),
                ('value3', models.IntegerField(null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tofl', to='cloudapp.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='LdrData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('number', models.IntegerField()),
                ('value1', models.IntegerField(null=True)),
                ('value2', models.IntegerField(null=True)),
                ('value3', models.IntegerField(null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ldr', to='cloudapp.vehicles')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=20)),
                ('value1', models.IntegerField(null=True)),
                ('value2', models.IntegerField(null=True)),
                ('value3', models.IntegerField(null=True)),
                ('value4', models.IntegerField(null=True)),
                ('value5', models.IntegerField(null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('breakAction', models.BooleanField()),
                ('override', models.BooleanField()),
                ('speed', models.FloatField(default=0.0)),
                ('zone_coord1', models.IntegerField(null=True)),
                ('zone_coord2', models.IntegerField(null=True)),
                ('zone', models.IntegerField(null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='cloudapp.vehicles')),
            ],
        ),
    ]
