# Generated by Django 4.2.1 on 2023-09-21 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloudapp', '0002_rename_name_vehicles_organization_and_more'),
        ('tof', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentdata',
            name='value1',
        ),
        migrations.RemoveField(
            model_name='incidentdata',
            name='value2',
        ),
        migrations.RemoveField(
            model_name='incidentdata',
            name='value3',
        ),
        migrations.RemoveField(
            model_name='incidentdata',
            name='value4',
        ),
        migrations.RemoveField(
            model_name='incidentdata',
            name='value5',
        ),
        migrations.RemoveField(
            model_name='incidentdata',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='incidentdata',
            name='zone_coord1',
        ),
        migrations.RemoveField(
            model_name='incidentdata',
            name='zone_coord2',
        ),
        migrations.RemoveField(
            model_name='ldrdata',
            name='number',
        ),
        migrations.AddField(
            model_name='incidentdata',
            name='LdrValue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ldr', to='tof.ldrdata'),
        ),
        migrations.AddField(
            model_name='incidentdata',
            name='ToflValue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tofl', to='tof.tofdata1'),
        ),
        migrations.AddField(
            model_name='incidentdata',
            name='TofmValue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tofm', to='tof.tofdata'),
        ),
        migrations.AddField(
            model_name='incidentdata',
            name='TofrValue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tofr', to='tof.tofdata2'),
        ),
        migrations.AddField(
            model_name='incidentdata',
            name='VizValue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viz', to='tof.vizdata'),
        ),
        migrations.AddField(
            model_name='incidentdata',
            name='zones',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ldrdata',
            name='value10',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ldrdata',
            name='value4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ldrdata',
            name='value5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ldrdata',
            name='value6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ldrdata',
            name='value7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ldrdata',
            name='value8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ldrdata',
            name='value9',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='incidentdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ldrdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tofdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tofdata1',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tofdata2',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vizdata',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vizdata',
            name='value2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('mode', models.CharField(default='override', max_length=255)),
                ('speed', models.FloatField(default=0.0)),
                ('zones', models.CharField(max_length=255)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Info', to='cloudapp.vehicles')),
            ],
        ),
    ]
