# Generated by Django 4.2.1 on 2023-10-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tof', '0002_remove_incidentdata_value1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AmbientConditions',
        ),
        migrations.DeleteModel(
            name='SystemOwner',
        ),
        migrations.AlterField(
            model_name='incidentdata',
            name='description',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
